"use strict";

var assert = require("node:assert/strict");
var fs = require("node:fs");
var path = require("node:path");

var root = path.resolve(__dirname, "..");
var content = fs.readFileSync(path.join(root, "content/content.js"), "utf8");
var worker = fs.readFileSync(path.join(root, "background/service-worker.js"), "utf8");
var options = fs.readFileSync(path.join(root, "options/options.js"), "utf8");

assert.match(content, /for \(var index = 0; index < scope\.targets\.length; index \+= 1\)/);
assert.match(content, /type: "oic:start-bulk-target", target: target/);
assert.match(content, /type: "oic:get-runtime-options"/);
assert.match(content, /enable-only; it never unchecks these options/);
assert.match(content, /runtimeOptions: runtimeOptions/);
assert.doesNotMatch(content, /send\(\{ type: "oic:start-bulk", targets:/);
assert.match(content, /function refreshIntegrationsAfterBulk\(\)/);
assert.match(content, /window\.location\.reload\(\)/);
assert.match(content, /refreshIntegrationsAfterBulk\(\);/);
assert.match(content, /function crossCheckMessage\(results\)/);
assert.match(content, /payload validation enabled/);
assert.match(content, /if \(!verified\.length\) return null/);
assert.doesNotMatch(content, /No runtime settings could be read back from OIC/);
assert.match(content, /sessionStorage\.setItem\("oic-bulk-cross-check"/);
assert.match(content, /function oicOverlayVisible\(\)/);
assert.match(content, /function bulkAnchor\(\)/);
assert.match(content, /return create\.closest\("oj-button"\) \|\| create\.closest\("button,a,\[role=button\]"\) \|\| create/);
assert.match(content, /anchor\.insertAdjacentElement\("afterend", wrap\)/);
assert.match(content, /does not wrap, replace, hide, or restyle Create/);
assert.doesNotMatch(content, /ensureRoot\(\)\.appendChild\(wrap\)/);

assert.match(worker, /message\.type === "oic:start-bulk-target"/);
assert.match(worker, /message\.type === "oic:get-runtime-options"/);
assert.match(worker, /async function startBulkTarget\(target, sourceTabId, requestedRuntimeOptions\)/);
assert.match(worker, /allowRunAgain: !!runtimeOptions\.allowRunAgain/);
assert.match(worker, /payloadValidation: !!runtimeOptions\.payloadValidation/);
assert.match(worker, /Refresh this OIC Integrations tab, then run Apply Debug Settings again/);
assert.doesNotMatch(worker, /async function startBulkOperation\(/);
assert.match(worker, /async function startBulkTarget\(target, sourceTabId, requestedRuntimeOptions\)/);
assert.match(worker, /preserveActivationOptions: false/);
assert.match(worker, /requireActive: true/);
assert.match(worker, /runUiProvider\("activate-debug", target, prefs, operationState\)/);
assert.match(worker, /var closeHelperWhenFinished = operation === "activate-debug" && helper\.id !== source\.id/);
assert.match(worker, /finally \{\s*if \(closeHelperWhenFinished\) await closeHelperTab\(helper\.id\);/);
assert.match(worker, /async function closeHelperTab\(tabId\)/);
assert.match(worker, /if \(traceChanged\) trace\.click\(\)/);
assert.match(worker, /status: "skipped-already-configured"/);
assert.match(worker, /status: "skipped-locked"/);
assert.match(worker, /if \(!changed\) return \{ text: text, changed: false, value: value \};\s*box\.click\(\)/);
assert.match(worker, /async function setDialogCheckbox\(text, value\)/);
assert.match(worker, /if \(prefs\.allowRunAgain\) runtimeOptions\.push\(await setDialogCheckbox\("allow to run again", true\)\)/);
assert.match(worker, /if \(prefs\.payloadValidation\) runtimeOptions\.push\(await setDialogCheckbox\("enable payload validation", true\)\)/);
assert.match(worker, /Set and confirm each option before touching the next one/);
assert.match(worker, /function dialogCheckboxChecked\(text\)/);
assert.match(worker, /Prefer the real input addressed by OIC's label/);
assert.match(worker, /labeledInput\.tagName === "INPUT" && labeledInput\.type === "checkbox"/);
assert.match(worker, /never "turn it off"/);
assert.doesNotMatch(worker, /\.checked = value/);
assert.doesNotMatch(worker, /option\.box\.checked/);
assert.doesNotMatch(worker, /\(semanticLabel \|\| box\)\.click\(\)/);
assert.match(worker, /new CustomEvent\("ojAction"/);
assert.match(worker, /were updated successfully\|tracing is enabled/);
assert.match(worker, /eventually\(activationSubmissionAccepted, 8000/);
assert.match(worker, /async function inspectActivationRuntimeOptions\(target, prefs\)/);
assert.match(worker, /Verifying Debug runtime options/);
assert.match(worker, /payload validation=.*after Save/);
assert.match(worker, /Configure activation is saved exactly once/);
assert.doesNotMatch(worker, /Retrying missing Debug runtime options/);
assert.doesNotMatch(worker, /var retry = await execute\(helper\.id, executeUiFlow/);
assert.match(worker, /verification: runtimeVerified && runtimeVerified\.options/);
assert.match(worker, /async function verifyActivationRuntimeOptions\(tabId, target, prefs\)/);
assert.match(worker, /for \(var attempt = 0; attempt < 3; attempt \+= 1\)/);
assert.doesNotMatch(worker, /if \(!trace\) throw new Error\([^\n]+\);\n\s+trace\.click\(\)/);
assert.doesNotMatch(worker, /unlockAction\.click\(\)/);
assert.doesNotMatch(worker, /unlockConfirm\.click\(\)/);
assert.doesNotMatch(worker, /findNamed(?:IncludingHidden)?\(\["delete"/i);
assert.doesNotMatch(worker, /delete integration/i);
assert.match(worker, /Configure activation lives in the row's Actions menu; never use the[\s\S]*?could deactivate it\./);

assert.match(options, /async function loadSettings\(\)/);
assert.match(options, /Saved and verified:/);
assert.match(options, /Chrome did not persist the selected runtime settings/);
assert.match(options, /Could not load extension settings:/);
assert.match(options, /finally \{ save\.disabled = false; \}/);

console.log("bulk orchestration tests passed");
